import Modal from "../mcomponents/Modal";
import {GoBell} from "react-icons/go";
import Button from "../mcomponents/Button";
import {useState} from "react";
import {CgClose} from "react-icons/cg";

function ModalWindowPage() {
    const [showModal, setShowModal] = useState(false)
    const handleClick = (event) => {
        setShowModal(true)
    }

    const handleClose = () => {
        setShowModal(false)
    }

    const actionButton = (
        <div>
            <Button secondary={true} onClick={ handleClose } className="mr-5"><CgClose />Close Modal</Button>
        </div>
    );

    const modal = <Modal onClose={handleClose} actionButton={actionButton}>
        <p>Model text content</p>
    </Modal>;
    return (
        <div className="relative">
            <div>
                <Button primary={true} rounded={true} onClick={handleClick} className="mr-5"><GoBell />Open Modal</Button>
            </div>
            <div>
                { showModal && modal }
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit hendrerit ex, eu lacinia est dictum sit amet. Nam ut elit sed sem congue auctor vitae fermentum erat. Mauris vitae consequat risus. Morbi ultricies velit dui, ut cursus nulla dapibus vel. Ut aliquam mauris lacinia ipsum blandit, a semper ante accumsan. Maecenas lobortis tempus bibendum. Ut molestie malesuada gravida. Donec aliquet suscipit sem a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla bibendum consectetur scelerisque. Aenean in finibus mi. Quisque volutpat venenatis leo blandit posuere. Nam ac elit tempor, egestas est et, rutrum massa. Sed egestas felis nulla, id mattis justo convallis at.</p>

        </div>
    );
}

export default ModalWindowPage;